name: CoderCo Practice

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest



    steps:
     - name: checkout
       uses: actions/checkout@v2

     - name: printing text
       run: echo "Hello World!!!"


